{% set name = "hipscat" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/astronomy-commons/hipscat/archive/v{{ version }}.tar.gz
  sha256: 0c6935b439c08e4bb5a72d69a04ed16ab110935a9370130d10f84b6c28556569

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9,<3.12
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - astropy
    - fsspec <=2023.9.2
    - healpy
    - numba
    - pandas
    - pyarrow >=10.0.0
    - typing-extensions >=4.3.0

test:
  imports:
    - hipscat
  commands:
    - pip check
    - pytest tests
  requires:
    - pip
    - pytest
    - pytest-mock
    - pytest-timeout
  source_files:
    - tests

about:
  home: https://github.com/astronomy-commons/hipscat
  summary: 'A HiPSCat astronomical catalog format reader library'
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mjuric
    - jeremykubica
    - drewoldag
    - delucchi-cmu
    - camposandro
